Update patch set 2
Patch Set 2:

I suspect a CL from this topic broke compilation of the target "docs" on two different branches:

vendor/unbundled_google/libraries/openglhelper/jni/gl_code.cpp:3:10: fatal error: 'nativehelper/jni.h' file not found
#include <nativehelper/jni.h>
^~~~~~~~~~~~~~~~~~~~
1 error generated.

Patch-set: 2
CC: Tobias Thierer <1103203@85c56323-6fa9-3386-8a01-6480fb634889>