Update patch set 1
Patch Set 1:

Ying,

Using that method breaks liblog (and possibly other things) in ways that don't seem entirely very easy to fix.

host SharedLib: liblog (out/host/linux-x86/obj/lib/liblog.so)
/android/source/prebuilts/gcc/linux-x86/host/i686-linux-glibc2.7-4.6/bin/../sysroot/usr/lib/Scrt1.o: In function `_start':
(.text+0x28): undefined reference to `main'
collect2: ld returned 1 exit status

Patch-set: 1