Revert "Add libstagefright_omx_soft to vndk"
This reverts commit cb867c9a9695cb6b14916e624df5fb049fc5c457.

Reason for revert: more build break on below, revet it together.

Removed VNDK-core: libstagefright_omx_soft.so
error: VNDK library list has been changed.
Run update-vndk-list.sh to update build/make/target/product/gsi/current.txt

Change-Id: I4846cdfe612c01cf9f9cab5a077a5782ff52e915